### ISSUE TITLE
감사합니다!

### ISSUE THREAD

**Issue by yunho-c** [Piorosen/Benchmark-Inference-Engine#6]
안녕하세요, readme에 정리해주신 자료 유익하게 보았습니다 :) 

성공적으로 벤치마크를 진행하셨나요? 결과를 얻으셨다면 혹시 공유가 가능하신지 궁금합니다!
ㄴ 모바일 개발에 익숙치 않아서, 환경 셋업을 공유해주시면 저도 돌려보고 결과에 추가하겠습니다

**Comment by Piorosen** [comment]
세상에나, 거의 반쯤 기록용으로 작성한 레포지토리에 관심을 가져 주셔서 우선 감사합니다.
제가 현재 진행 중인 연구 및 벤치는 현재 Arm CPU를 대상으로 진행한 결과 인 것을 우선 명심해 주셔야할 부분입니다.
 * 안타깝게도 기록 공유는 어려울것 같습니다.

> 성능으로 최적화를 진행하는 것이 좋을까요? 가져오시면 공유가 가능하신지 문의합니다!
특정 상황에 따라서, TVM 보다 ONNXRuntime이 더 우수한 성능을 나타내기도 하였습니다.

> 모바일 개발에 성공하게 되면 환경 셋업을 공유하면 복원 반환 결과에 추가하겠습니다.
안드로이드의 경우에는 간단하게 테스트해 보기 위해서 Xamarin과 C#의 Nuget 패키지를 활용했습니다.

**Comment by Piorosen** [comment]
@k2m5t2 
만약 안드로이드에서 C++ 개발이 필요하시다면, 아래의 레포지토리를 확인 하시면 개발 환경 셋팅에 도움이 될것으로 보입니다. 
아니라면, Termux 라는 안드로이드 앱 또한 추천드립니다.
termux는 안드로이드 adb 쉘을 기반으로 하여 만들어진 가상 터미널 입니다. (가상 머신이 아닙니다.)

https://github.com/Piorosen/Restbed-based-Android-Web-Server
